# Generated by Django 5.2.12 on 2026-03-30 21:46

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobreqresult',
            name='jobKeyword',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobreqresult',
            name='jobLocation',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobreqresult',
            name='jobRemote',
            field=models.TextField(default=datetime.datetime(2026, 3, 30, 21, 44, 26, 866813, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobreqresult',
            name='jobType',
            field=models.TextField(default=datetime.datetime(2026, 3, 30, 21, 46, 19, 311711, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
