# Generated by Django 5.2.12 on 2026-04-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobreqresult_jobkeyword_jobreqresult_joblocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblistingresult',
            name='company_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='joblistingresult',
            name='company_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='joblistingresult',
            name='job_function',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='joblistingresult',
            name='job_industries',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='joblistingresult',
            name='job_location',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
