# Generated by Django 5.2.12 on 2026-04-01 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_joblistingresult_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobreqresult',
            name='prompt',
        ),
    ]
