# Generated by Django 5.2.12 on 2026-04-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_jobreqresult_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='source',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
