# Generated by Django 5.2.12 on 2026-04-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_snapshot_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblistingresult',
            name='source',
            field=models.CharField(default='NONE', max_length=50),
            preserve_default=False,
        ),
    ]
