# Generated by Django 5.2.12 on 2026-04-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_joblistingresult_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblistingresult',
            name='applied',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='joblistingresult',
            name='date_applied',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblistingresult',
            name='date_interested',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblistingresult',
            name='date_rejected',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblistingresult',
            name='interested',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='joblistingresult',
            name='rejected',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
    ]
