# Generated by Django 5.2.12 on 2026-04-17 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_joblistingresult_applied_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblistingresult',
            name='applied',
        ),
        migrations.RemoveField(
            model_name='joblistingresult',
            name='rejected',
        ),
    ]
