# Generated by Django 5.2.12 on 2026-04-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_remove_joblistingresult_applied_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblistingresult',
            old_name='date_applied',
            new_name='applied_date',
        ),
        migrations.RenameField(
            model_name='joblistingresult',
            old_name='date_interested',
            new_name='interested_date',
        ),
        migrations.RenameField(
            model_name='joblistingresult',
            old_name='date_rejected',
            new_name='status_date',
        ),
        migrations.AddField(
            model_name='joblistingresult',
            name='applied',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='joblistingresult',
            name='status',
            field=models.CharField(blank=True, choices=[('waiting', 'Waiting for first Response'), ('rejected', 'Rejected'), ('interview', 'Interview Pending')], max_length=30, null=True),
        ),
    ]
